### ISSUE TITLE
未响应

### ISSUE THREAD

**Issue by yuwan-jpg** [foryujian/yujianrdpcrack#1]
1.线程超过20，或者主机列表过多；容易假死。查看任务管理器显示已暂停
2.不能停止线程，点击停止等待时间过长

**Comment by yuwan-jpg** [comment]
[![](https://i.loli.net/2019/05/08/5cd29154d890f.png)](https://i.loli.net/2019/05/08/5cd29154d890f.png)

**Comment by foryujian** [comment]
第一个版本存在不少问题，已经全部修复了，但是不再提供测试了，假死是因为模式窗口挂起了UI！
